##MULTIPLE LINEAR REGRESSION MODEL

Home price prediction

***TASK***

***Given these home prices find out price of a home that has,***

***3000 sqr ft area, 3 bedrooms, 40 year old***

***2500 sqr ft area, 4 bedrooms, 5 year old***

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#loding the dataset .
df=pd.read_csv("/content/drive/MyDrive/homeprices_MLP.csv")
df.head(5)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

The linear equation for this data would be

price = m1 * area + m2 * bedrooms + m3 * age + b



In [ ]:
#handling missing values
df.bedrooms.median()

4.0

In [ ]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [ ]:
#coefficients M1.M2 and M3 respectively
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
#value of b
reg.intercept_

221323.00186540396

To find price for

3000 sqr ft area, 3 bedrooms, 40 year old

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

***PRICE IS 498409***

To find price for

2500 sqr ft area, 4 bedrooms, 5 year old

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

***PRICE IS 578877***

***EXERCISE***

The data contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

***2 yr experience, 9 test score, 6 interview score***

***12 yr experience, 10 test score, 10 interview score***

In [ ]:
df1=pd.read_csv("/content/drive/MyDrive/hiring.csv")
df1.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [ ]:
df1.experience = df1.experience.fillna("zero")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
!pip install word2number

In [ ]:
from word2number import w2n
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(df1['test_score(out of 10)'].median())
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
df1.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()